platform: x64

environment:
  matrix:
    - PYTHON: 'C:\\Python27'
      PYTHON_VERSION: '2.7.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python27-x64'
      PYTHON_VERSION: '2.7.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python35'
      PYTHON_VERSION: '3.5.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python35-x64'
      PYTHON_VERSION: '3.5.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python36'
      PYTHON_VERSION: '3.6.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python36-x64'
      PYTHON_VERSION: '3.6.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python37'
      PYTHON_VERSION: '3.7.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python37-x64'
      PYTHON_VERSION: '3.7.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python38'
      PYTHON_VERSION: '3.8.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python38-x64'
      PYTHON_VERSION: '3.8.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python39'
      PYTHON_VERSION: '3.9.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python39-x64'
      PYTHON_VERSION: '3.9.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python310'
      PYTHON_VERSION: '3.10.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python310-x64'
      PYTHON_VERSION: '3.10.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python311'
      PYTHON_VERSION: '3.11.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python311-x64'
      PYTHON_VERSION: '3.11.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python312'
      PYTHON_VERSION: '3.12.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python312-x64'
      PYTHON_VERSION: '3.12.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python313'
      PYTHON_VERSION: '3.13.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python313-x64'
      PYTHON_VERSION: '3.13.x'
      PYTHON_ARCH: '64'

    - PYTHON: 'C:\\Python314'
      PYTHON_VERSION: '3.14.x'
      PYTHON_ARCH: '32'

    - PYTHON: 'C:\\Python314-x64'
      PYTHON_VERSION: '3.14.x'
      PYTHON_ARCH: '64'

init:
  - 'ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%'

install:
  - set 'PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Tools\\Scripts;%PATH%'
  - python -m pip install --upgrade pip
  - pip install paramiko mock pytest pytest-cov pytest-xdist

build: off

test_script:
  - python setup.py install
  - pytest --showlocals --durations=10 -n 4 tests
