[tox]
envlist = syntax, py{27,34,35,36,37,38,39,310,311,312,313,314}, docs

[testenv]
deps = 
    paramiko
    -r {toxinidir}/tests/requirements.txt
commands =
    pytest tests \
        --showlocals \
        --durations=10 \
        -n auto \
        --cov=sshtunnel \
        --cov-report=html:test_results/coverage.html \
        --cov-report=term \
        --junit-xml=test_results/report.xml

[testenv:docs]
changedir = docs
deps =
    paramiko
    -r {toxinidir}/docs/requirements.txt
commands=
    sphinx-build \
        -WavE \
        -b html \
        -d {envtmpdir}/_build/doctrees \
        . \
        {envtmpdir}/_build/html

[testenv:syntax]
basepython = python
skip_install = True
deps =
    -r {toxinidir}/tests/requirements-syntax.txt
commands =
    check-manifest --ignore tox.ini,tests*,*.yml
    python setup.py sdist
    twine check dist/*
    flake8 --exclude .venv,build,docs,e2e_tests --max-complexity 10 --ignore=W503
    bashtest README.rst
