version: 2.1

executors:
  python_base:
    parameters:
      version:
        type: string
        default: "3.10"
    docker:
      - image: cimg/python:<< parameters.version >>

commands:
  install_deps:
    description: Install dependencies

    parameters:
      include_syntax:
        type: boolean
        default: false
      include_test:
        type: boolean
        default: false
      include_docs:
        type: boolean
        default: false

    steps:
      - restore_cache:
          keys:
            - v2-sshtunnel-{{ arch }}-{{ checksum "setup.py" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "tests/requirements-syntax.txt" }}
            - v2-sshtunnel-{{ arch }}-
      - run:
          name: Install sshtunnel
          command: >-
            pipenv
            --python $(which python)
            install
            --skip-lock
            -e
            .
      - when:
          condition: << parameters.include_syntax >>
          steps:
            - run:
                name: Install syntax dependencies
                command: >-
                  pipenv
                  --python $(which python)
                  install
                  --skip-lock
                  --dev
                  -r tests/requirements-syntax.txt
      - when:
          condition: << parameters.include_test >>
          steps:
            - run:
                name: Install dev dependencies
                command: >-
                  pipenv
                  --python $(which python)
                  install
                  --skip-lock
                  --dev
                  -r tests/requirements.txt
      - when:
          condition: << parameters.include_docs >>
          steps:
            - run:
                name: Install docs dependencies
                command: >-
                  pipenv
                  --python $(which python)
                  install
                  --skip-lock
                  --dev
                  -r docs/requirements.txt
      - save_cache:
          key: v2-sshtunnel-{{ arch }}-{{ checksum "setup.py" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum "tests/requirements-syntax.txt" }}
          paths:
            - .venv/

jobs:
  tests:
    description: Run test suite for each python version

    parameters:
      version: { type: string }

    executor: { name: python_base, version: << parameters.version >> }

    steps:
      - checkout
      - install_deps: { include_test: true }
      - run:
          name: Run test suite
          command: >-
            pipenv
            run pytest tests
            --showlocals
            --durations=10
            -n auto
            --cov=sshtunnel
            --cov-report=html:test_results/coverage.html
            --cov-report=term
            --junit-xml=test_results/report.xml
      - run:
          name: Move coverage file
          command: |
            mv .coverage .coverage.<< parameters.version >>
      - persist_to_workspace:
          root: .
          paths:
            - .coverage.*
      - store_test_results:
          path: test_results

  upload_coverage:
    description: Upload coverage to coveralls

    executor: { name: python_base }

    steps:
      - checkout
      - attach_workspace: { at: . }
      - install_deps: { include_test: true }
      - run:
          name: Combine coverage files
          command: >-
            pipenv
            run coverage combine .coverage.*
      - run:
          name: Upload to Coveralls
          command: >-
            pipenv
            run coveralls

  package:
    description: Build artifacts

    executor: { name: python_base }

    steps:
      - checkout
      - install_deps: { include_test: true }
      - run:
          name: Build artifact
          command: >-
            pipenv
            run python setup.py bdist_wheel sdist
      - run:
          name: Check artifacts
          command: >-
            pipenv
            run twine check dist/*
      - persist_to_workspace:
          root: .
          paths: [dist/*]

  deploy_pypi:
    description: Upload artifacts to PyPI

    parameters:
      repository: { type: string, default: "testpypi" }
      token_env: { type: env_var_name, default: TESTPYPI_TOKEN }

    executor: { name: python_base }

    steps:
      - checkout
      - install_deps: { include_test: true }
      - attach_workspace: { at: . }
      - run:
          name: Upload to TestPyPI
          command: >-
            pipenv
            run
            twine upload
            --repository << parameters.repository >>
            --username __token__
            --password ${<< parameters.token_env >>}
            --skip-existing
            dist/*

  docs:
    description: Produce documentation from source

    executor: { name: python_base }

    steps:
      - checkout
      - install_deps: { include_docs: true }
      - run:
          name: Build documentation
          command: >-
              pipenv
              --python $(which python)
              run sphinx-build
              -WavE
              -b html docs _build/html
      - store_artifacts:
          path: _build/html
          destination: sshtunnel-docs

  syntax:
    description: Run syntax validation tests

    executor: { name: python_base }

    steps:
      - checkout
      - install_deps: { include_syntax: true }
      - run:
          name: checking MANIFEST.in
          command: >-
            pipenv
            run check-manifest
            --ignore tox.ini,tests*,*.yml
      - run:
          name: creating source distribution
          command: >-
            pipenv
            run python setup.py sdist
      - run:
          name: checking distribution description
          command: >-
            pipenv
            run twine check dist/*
      - run:
          name: linting and checking python code formatting
          command: >-
            pipenv
            run flake8
            --exclude .venv,build,docs,e2e_tests
            --max-complexity 10
            --ignore=W503
      - run:
          name: checking CLI help
          command: >-
            pipenv
            run bashtest README.rst

workflows:
  version: 2

  documentation:
    jobs:
      - docs

  check_build_deploy:
    jobs:
      - syntax
      - tests:
          requires: [syntax]
          matrix:
            parameters:
              version:
                - "2.7"
                - "3.5"
                - "3.6"
                - "3.7"
                - "3.8"
                - "3.9"
                - "3.10"
                - "3.11"
                - "3.12"
                - "3.13"
                - "3.14"
      - upload_coverage:
          requires: [tests]
      - package:
          requires: [tests]
      - deploy_pypi:
          name: test_deploy
          requires: [package]
      - hold:
          type: approval
          requires: [test_deploy]
          filters: { branches: { only: master } }
      - deploy_pypi:
          name: production_deploy
          repository: pypi
          token_env: PYPI_TOKEN
          requires: [hold]
          filters: { branches: { only: master } }
